### ISSUE TITLE
Consider an open-source license

### ISSUE THREAD

**Issue by evan-goode** [craftycodie/OnlineModeFix#9]
Hi, I would like to fork this and get it working with my self-hosted authentication server, [Drasl](https://github.com/unmojang/drasl). Would you consider publishing it under an open-source license (e.g. MIT, GPLv3), or is this proprietary software?

Regardless, please add a LICENSE file to the repository to make it clear. Thanks!

**Comment by craftycodie** [comment]
Added :)

**Comment by evan-goode** [comment]
Thank you!
